### ISSUE TITLE
我如何正常的启动它?

### ISSUE THREAD

**Issue by wangjian81** [ctripcorp/flybirds#10]
系统版本:  masOS big Sur  11.6 
python版本 :      3.8.9
pip3 install flybirds 之后 , flybirds 我无法正常启动它.

**Comment by DHpie** [comment]
flybirds 安装后，可以使用脚手架创建一个Demo项目，项目启动可以参考以下几点：

1. 环境搭建：https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#id5
2. 运行前检查： https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#id14

**Comment by wangjian81** [comment]
OK 我已处理,是我的环境变量问题无法找到可执行文件.
