### ISSUE TITLE
flutterApp能够正常使用它吗?

### ISSUE THREAD

**Issue by wangjian81** [ctripcorp/flybirds#11]
希望得到帮助,通过提供的例子能获取到flutterApp界面元素吗?

**Comment by wangjian81** [comment]
<img width="448" alt="截屏2022-03-11 上午11 01 27" src="https://user-images.githubusercontent.com/76034348/157794081-530b8a15-a478-4593-9554-7e7a7f8a9181.png">
类似于这样的一个flutter应用的按钮,我应该如何获取它,并且点击它?

**Comment by DHpie** [comment]
对于flutterApp 界面元素，poco 官方的回复是：暂不支持 这种页面，会出现部分控件拿不到的情况
poco的支持情况可以参考： https://airtest.doc.io.netease.com/IDEdocs/poco_framework/1_poco_info/#3-poco

**Comment by clgwlg** [comment]
后续的v0.3版本，我们会考虑通过图像识别的方式，处理poco无法识别的界面元素，理论上也可以支持flutter app元素

**Comment by wangjian81** [comment]
期待

**Comment by clgwlg** [comment]
0.3版本已经上线，你可以使用OCR功能，进行flutter app的见面元素获取和检查

**Comment by andychan06** [comment]
![Screenshot 2022-07-20 at 2 15 58 PM](https://user-images.githubusercontent.com/95615371/179910227-837dfbfb-09bb-4791-af08-c1392dc8c255.png)
<img width="746" alt="Screenshot 2022-07-20 at 12 36 29 PM" src="https://user-images.githubusercontent.com/95615371/179910241-305d7bc3-8bd9-4399-9772-3b1d42b96710.png">

Flutter app 使用OCR功能 掃描 繁体中文 | chinese_cht 有時候文字不正確 
例如 [輸入手機號碼繼續] 變成 [輸公手機號碼繼續] 

請問有方法解決嗎，還是要到 PaddleOCR 尋求解決?

**Comment by andychan06** [comment]
> 首先，请先检查一下"flybirds_config.json" 中的配置项 "ocrLang", 是否已使用繁体中文特征库 ？ 繁体中文扫描，需要配置为 `"ocrLang": "chinese_cht" `

上面個結果是已設定了 "ocrLang": "chinese_cht"

**Comment by clgwlg** [comment]
好的，这个问题，确实需要到 PaddleOCR 尋求解決了，可能是PaddleOCR的Bug 。

**Comment by andychan06** [comment]
> 好的，这个问题，确实需要到 PaddleOCR 尋求解決了，可能是PaddleOCR的Bug 。

明白，那麼除了OCR，還有其他方法可以應用到Flutter App嗎？

**Comment by clgwlg** [comment]
暂时只有OCR，我们规划在下个月的版本中支持图像扫描，到时可以作为OCR的补充，解决这个问题。

**Comment by andychan06** [comment]
好的，謝謝 
期待你們下一個版本

**Comment by clgwlg** [comment]
> 好的，謝謝 期待你們下一個版本

我们在v0.3.5 版本中支持了ocr错误矫正，可以尝试一下。
https://github.com/ctripcorp/flybirds/releases/tag/v0.3.5
