### ISSUE TITLE
[BUG] install fail on macOS

### ISSUE THREAD

**Issue by prife** [ctripcorp/flybirds#12]
**问题描述 / Describe the bug**

install fail on macOS, cause flybirds depend on a lower version tidevice 0.5.9

**问题复现步骤 / To Reproduce**

```
Collecting flybirds
  Downloading flybirds-0.1.6-py3-none-any.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 2.6 MB/s
  Downloading flybirds-0.1.5-py3-none-any.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 2.7 MB/s
  Downloading flybirds-0.1.4-py3-none-any.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 2.6 MB/s
  Downloading flybirds-0.1.3-py3-none-any.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 2.7 MB/s
  Downloading flybirds-0.1.2-py3-none-any.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 2.6 MB/s
  Downloading flybirds-0.1.1-py3-none-any.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 2.7 MB/s
ERROR: Cannot install flybirds==0.1.1, flybirds==0.1.2, flybirds==0.1.3, flybirds==0.1.4, flybirds==0.1.5 and flybirds==0.1.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    flybirds 0.1.6 depends on tidevice==0.5.9
    flybirds 0.1.5 depends on tidevice==0.5.9
    flybirds 0.1.4 depends on tidevice==0.5.9
    flybirds 0.1.3 depends on tidevice==0.5.9
    flybirds 0.1.2 depends on tidevice==0.5.9
    flybirds 0.1.1 depends on tidevice==0.5.9

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
WARNING: You are using pip version 21.2.4; however, version 22.0.4 is available.
You should consider upgrading via the '/Users/wetest/.pyenv/versions/3.9.10/bin/python3.9 -m pip install --upgrade pip' command.
FAIL: 1
```

**预期结果 / Expected behavior**

should support with the newest tidevice

**截图 / Screenshots**

<img width="902" alt="企业微信截图_d96f13b4-0a15-4006-b01c-762c0b166a0f" src="https://user-images.githubusercontent.com/1572684/162608937-cd449618-dadf-4629-9f05-84fa9d8c1d7b.png">

**环境信息 / Environment (please complete the following information):**
 - OS: macOS 12.0.1

**Comment by DHpie** [comment]
Normally, `pip3 install` only downloads the latest version of the package, but from your screenshot, it seems that you downloaded all versions of `flybirds `at the same time, thus causing a version dependency conflict.
We recommend that you try to specify the version when downloading: Pip3 install Flybirds ==0.1.6

**Comment by prife** [comment]
>pip3 install only downloads the latest version of the package, but from your screenshot, it seems that you downloaded all versions of flybirds at the same time
it's pip's bug, see: https://github.com/pypa/pip/issues/9284

I've installed the newest pip(version==22.0.4), but flybirds still can't be installed on m1 mac.
numpy==1.19.3 is not supported on m1 macOS 12.0.1

**Comment by DHpie** [comment]
Thank you for the information. There is already a related issue with airtes(see: https://github.com/AirtestProject/Airtest/issues/1022) , and we will continue to follow this issue.

**Comment by DHpie** [comment]
A new version of `airtest v1.2.5` has been released. This version removes the restriction on the `numpy `version number during installation. You can try it again
