### ISSUE TITLE
创建项目的时候报错Error!! create project test has error, errMsg: copytree() got an unexpected keyword argument 'dirs_exist_ok'

### ISSUE THREAD

**Issue by moriweiji** [ctripcorp/flybirds#162]
**问题描述 / Describe the bug**
Welcome to flybirds cli. Please enter any information to continue.
Please input your project name>>: test
Please input your test platform? (Android/IOS/Web): android
Do you want to configure your deviceId now?(this step can be skipped) [y/N]: y
Please input your deviceId?:
Please input your deviceId?: 192.168.2.82:20082
Do you want to configure your packageName now?(this step can be skipped) [y/N]: n
You can configure your packageName later in the project's flybirds_config.json file.
Cloning into 'test'...
Processing  [------------------------------------]    0%
Error!! create project test has error, errMsg: copytree() got an unexpected keyword argument 'dirs_exist_ok'

**问题复现步骤 / To Reproduce**
创建项目的时候  (flybird-eIzvST0V) D:\work\huihe\flybird>flybirds create

**截图 / Screenshots**
![image](https://user-images.githubusercontent.com/18164265/230348436-89f174d9-7ffa-4853-8719-6c79b2e0522c.png)

**环境信息 / Environment (please complete the following information):**
- win10
- python3.7

**Comment by zhouxu1111** [comment]
试下python3.8，shutil.py的copytree的dirs_exist_ok只定义3.8版本以上。[参考：https://stackoverflow.com/questions/63661976/problems-using-shutil-copytree-in-python] 另：也可修改copytree方法，加入参数dirs_exist_ok=True[默认False]。
