### ISSUE TITLE
怎么自定义setup和teardown，虽然源码里面有说明hook类的逻辑，没看明白怎么在项目中实现

### ISSUE THREAD

**Issue by Ymars1990** [ctripcorp/flybirds#169]
怎么自定义setup和teardown，虽然源码里面有说明hook类的逻辑，没看明白怎么在项目中实现

**Comment by clgwlg** [comment]
项目中自定义hook的文件：pscript/dsl/hook.py，常用的有下面几种方式，你可以在这个文件里修改

1. before_all_extend：项目整体执行前触发
2. after_all_extend：项目之行结束后触发
3. before_feature_extend：项目中的每个feature文件执行前触发
4. after_feature_extend：项目中的每个feature文件执行后触发
5. before_scenario_extend：feature中的每个senario执行前触发
6. after_scenario_extend：feature中的每个senario执行后触发
7. before_step_extend：senario中的每个step执行前触发
8. after_step_extend：senario中的每个step执行后触发
