### ISSUE TITLE
操作语法中增加"循环"的功能

### ISSUE THREAD

**Issue by jasmineamber** [ctripcorp/flybirds#28]
**Is your feature request related to a problem? Please describe.**
场景: 答题功能, 答完一题, 出现下一题, 全部答完 **显示成绩** 页面

目前的功能似乎只能处理固定步骤的测试, 比如上面的场景, 如果题目的数量是不确定的, 没办法通过现有的功能判断出现 **成绩页面** 时结束测试.

**Describe the solution you'd like**
希望增加一个循环的功能, 比如: 当 **成绩页面** 出现时, 可以结束测试

**Comment by DHpie** [comment]
flybirds 提供了自定义step语法的的功能，用以支持公共语句不能满足自身项目的需求的情况。
具体可参考文档：[自定义step语句模板]( https://flybirds.readthedocs.io/zh_CN/latest/BDD-UI-Testing-Flybirds.html#id16)

**Comment by jasmineamber** [comment]
谢谢
