### ISSUE TITLE
元素定位支持xpath

### ISSUE THREAD

**Issue by jasmineamber** [ctripcorp/flybirds#29]
**Is your feature request related to a problem? Please describe.**
元素定位支持xpath

**Describe the solution you'd like**
目前web定位似乎用的page.query_selector, playwright支持page.locator同时兼容多种定位方式

**Comment by DHpie** [comment]
1. 目前web定位使用的是page.locator；
2.  playwright 的page.query_selector 同样也支持元素xpath 定位；参见：[page-query-selector](https://playwright.dev/python/docs/api/class-page#page-query-selector)

**Comment by DHpie** [comment]
元素定位使用的是`page.locator（get_ele_locator）`，判断元素是否存在用的是`query_selector（get_ele_handle）`。
不管是`query_selector`，还是`page.locator`，都支持xpath 定位的， 不用纠结。
