### ISSUE TITLE
[Feature] Add web BDD UI Testing support

### ISSUE THREAD

**Issue by clgwlg** [ctripcorp/flybirds#3]
**增加web BDD UI Testing支持**
* 通用语法与APP端保持一致
* 支持无头、有头浏览器模式
* 支持多种浏览器内核：chrome、firefox、webkit
* 支持并发执行模式

**Comment by yuti8307** [comment]
什么时候新版本能支持呢？

**Comment by clgwlg** [comment]
计划在4月初的v0.2版本，发布相关功能，到时欢迎使用，给出使用反馈和建议。

**Comment by omictree** [comment]
期待

**Comment by quyuan01** [comment]
发布了么

**Comment by clgwlg** [comment]
[v0.2版本](https://github.com/ctripcorp/flybirds/releases/tag/v0.2)已发布，支持Web BDD UI Testing，欢迎使用，给出反馈和建议。
