### ISSUE TITLE
支持设置浏览器语言环境

### ISSUE THREAD

**Issue by jasmineamber** [ctripcorp/flybirds#31]
**Is your feature request related to a problem? Please describe.**
支持在flybirds_config.json中设置browser locale

**Describe the solution you'd like**
同一个定位方式, 在不同的语言环境下可能会导致定位表现不一致

**Describe alternatives you've considered**
希望能通过配置文件自定义locale
```
context = browser.new_context(record_video_dir="videos",
                                      ignore_https_errors=True,
                                      locale="zh-CN")
```

**Comment by DHpie** [comment]
> 同一个定位方式, 在不同的语言环境下可能会导致定位表现不一致

可以举一个具体的例子吗？

**Comment by jasmineamber** [comment]
```
# language: zh-CN
功能: 测试程序

  # @dynamic
  场景: 调试
    假如 跳转页面到[https://jasmineamber.github.io/pages/API/modal/modal]
      而且 页面渲染完成出现元素[text=无标题的modal]
    假如 点击[text=无标题的modal]
      而且 页面渲染完成出现元素[.uni-modal__btn:has-text('确定')]
    那么 全屏截图
```

比如这个确认弹窗, 应该是用原生的 `confirm` 的实现的, 在不同的语言下 `确定/取消` 显示的不一样, 根据文字定位就会失败
![image](https://user-images.githubusercontent.com/13842833/169435056-c8127df2-8146-448e-bf0e-450d4ac70b85.png)

![image](https://user-images.githubusercontent.com/13842833/169435096-504bfd76-6972-417d-b0bf-4344450c8633.png)

**Comment by DHpie** [comment]
我大概理解你的需求。但是事实上假设我提供了 `locale` 配置，上述用例仍然是失败的。因为 [.uni-modal__btn:has-text('确定')] 中的 `确定` 无法替换为 `OK` ，它不由 `navigator.language` 控制，这是测试人员手动输入的。

所以这其实是2个独立的问题：
1. 我们目前没有提供 `locale ` 配置，所测试时没有办法选择需要的语言，后续版本我们会带上。
2. 上述这种情况下建议使用 xpath 、css或其它 相关的定位方式 可解决你的问题。另外，上面链接中的 comfire 不是原生的 comfire

**Comment by jasmineamber** [comment]
好的, 感谢
