### ISSUE TITLE
录屏中文字体小方块

### ISSUE THREAD

**Issue by wanghaisheng** [ctripcorp/flybirds#38]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

目前的实现里我没太看懂是怎么实现的，但有一个bug
如果是unbutu系统中没有中文字符，会显示小方块，同理cjk系列的语言应该都是这样
需要文档里注明提前安装对应字体
参考录屏中的字体显示
https://www.zhihu.com/question/19911793

sudo apt-get install ttf-wqy-microhei  #文泉驿-微米黑
sudo apt-get install ttf-wqy-zenhei  #文泉驿-正黑
sudo apt-get install xfonts-wqy #文泉驿-点阵宋体

**Comment by clgwlg** [comment]
感谢你的反馈，根据反馈，我们在文档中添加了对应的提醒。
