### ISSUE TITLE
screenshot step cannot cap image 

### ISSUE THREAD

**Issue by andychan06** [ctripcorp/flybirds#60]
**问题描述 / Describe the bug**
screenshot step succeed, but no image can be found. Also the time of screenshot in report shows 00:00:00.000

**问题复现步骤 / To Reproduce**
1. use Background with more than 2 steps
2. screenshot in Scenario
3. find screenshot  

**预期结果 / Expected behavior**
image should be found

**截图 / Screenshots**
![111](https://user-images.githubusercontent.com/95615371/177972982-415e036c-fbab-4ed6-9a20-05ec65bb4840.png)

**环境信息 / Environment (please complete the following information):**
 - Device: [Pixel 4A]
 - OS: [Android 12]

**Additional context**

**Comment by andychan06** [comment]
seems like /default/screen.py:

if len(scenario.steps) > step_index >= 0:

this guard makes screenshot not run?

**Comment by xiaoxiaocaiiao** [comment]
cannot repro please share the run log.  By the way do you find the msg "[screen_link_to_behave]" in the run log?

**Comment by andychan06** [comment]
> [screen_link_to_behave]

cannot find this message.

my test example from ctrip:

```
  # language: en
 Feature: flybirds test feature-android click

  Background: 
      When start app[ctrip.android.view]
      And page rendering complete appears element[text=机票]

   Scenario: test click--click position
     And  click position[580,1200]
     And  wait[5]seconds
     Then screenshot
     Then close app
```

And the result 
<img width="892" alt="Screenshot 2022-07-11 at 3 06 34 PM" src="https://user-images.githubusercontent.com/95615371/178208373-cd4842e3-87b4-490f-8393-9156b0e36507.png">

And the print log
[log.txt](https://github.com/ctripcorp/flybirds/files/9081632/log.txt)

There is nothing captured in the screenshot folder.

**Comment by xiaoxiaocaiiao** [comment]
een..., it seems that only before step hook is run, but screen step logical is skiped, please  debug as blow pic:
![image](https://user-images.githubusercontent.com/12480724/178215387-048ddcb6-e196-44f3-838f-0aaf171b4934.png)

run script please use( "./features/test/android/base_en_click.feature --format=json -o report/1ae9c606-8943-48ec-b0cb-b3e02239fb13/report.json --define screenShotDir=cmVwb3J0LzFhZTljNjA2LTg5NDMtNDhlYy1iMGNiLWIzZTAyMjM5ZmIxMy9zY3JlZW5zaG90 --define run_at=bG9jYWw= --no-color --no-capture --no-capture-stderr"  ) and tell me what heppen here.

**Comment by andychan06** [comment]
> een..., it seems that only before step hook is run, but screen step logical is skiped, please debug as blow pic: ![image](https://user-images.githubusercontent.com/12480724/178215387-048ddcb6-e196-44f3-838f-0aaf171b4934.png)
> 
> run script please use( "./features/test/android/base_en_click.feature --format=json -o report/1ae9c606-8943-48ec-b0cb-b3e02239fb13/report.json --define screenShotDir=cmVwb3J0LzFhZTljNjA2LTg5NDMtNDhlYy1iMGNiLWIzZTAyMjM5ZmIxMy9zY3JlZW5zaG90 --define run_at=bG9jYWw= --no-color --no-capture --no-capture-stderr" ) and tell me what heppen here.

The problem cannot be reproduced using the demo Ctrip project with my testing feature?

**Comment by xiaoxiaocaiiao** [comment]
yes

**Comment by andychan06** [comment]
tried your suggestion. 
[reproduce.txt](https://github.com/ctripcorp/flybirds/files/9088832/reproduce.txt)

Please have a look

**Comment by xiaoxiaocaiiao** [comment]
> tried your suggestion. [reproduce.txt](https://github.com/ctripcorp/flybirds/files/9088832/reproduce.txt)
> 
> Please have a look
when you complete my suggestion, you can hold on the below code when debug the test case, and see what happen here.
seems like /default/screen.py:

if len(scenario.steps) > step_index >= 0:

this guard makes screenshot not run?

**Comment by andychan06** [comment]
yes, the if statement guards the screenshot

![Screenshot 2022-07-12 at 11 07 13 AM](https://user-images.githubusercontent.com/95615371/178400238-fb753e8a-3d7f-482e-872f-9718a135c5b3.png)

```
 # language: en
 Feature: flybirds test feature-android click

  Background: 
      When start app[ctrip.android.view]
      And page rendering complete appears element[text=机票]

   Scenario: test click--click position
     And  click position[580,1200]
     And  wait[5]seconds
     Then screenshot
     Then close app
```

**Comment by xiaoxiaocaiiao** [comment]
> yes, the if statement guards the screenshot
> 
> ![Screenshot 2022-07-12 at 11 07 13 AM](https://user-images.githubusercontent.com/95615371/178400238-fb753e8a-3d7f-482e-872f-9718a135c5b3.png)
> 
> ```
>  # language: en
>  Feature: flybirds test feature-android click
> 
>   Background: 
>       When start app[ctrip.android.view]
>       And page rendering complete appears element[text=机票]
> 
>    Scenario: test click--click position
>      And  click position[580,1200]
>      And  wait[5]seconds
>      Then screenshot
>      Then close app
> ```
use the workaround : add background to scenario。 i will try to it and find the final solution。

**Comment by andychan06** [comment]
Thanks @xiaoxiaocaiiao, I have used the workaround already. 

Look forward to hearing any update.

**Comment by xiaoxiaocaiiao** [comment]
> Thanks @xiaoxiaocaiiao, I have used the workaround already.
> 
> Look forward to hearing any update.
fix in latest build.

**Comment by andychan06** [comment]
> > Thanks @xiaoxiaocaiiao, I have used the workaround already.
> > Look forward to hearing any update.
> > fix in latest build.

@xiaoxiaocaiiao thanks for the update. Tested the latest build & confirm it is fixed.
