### ISSUE TITLE
pip3 install flybirds  安装报错subprocess-exited-with-error

### ISSUE THREAD

**Issue by shijie233** [ctripcorp/flybirds#63]
Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [1102 lines of output]
      Ignoring numpy: markers 'python_version == "3.6"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8"' don't match your environment
      Collecting setuptools
        Using cached setuptools-63.2.0-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting scikit-build
        Using cached scikit_build-0.15.0-py2.py3-none-any.whl (77 kB)
      Collecting cmake
        Using cached cmake-3.22.5-py2.py3-none-macosx_10_10_universal2.macosx_10_10_x86_64.macosx_11_0_arm64.macosx_11_0_universal2.whl (75.2 MB)
      Collecting pip
        Using cached pip-22.1.2-py3-none-any.whl (2.1 MB)
      Collecting numpy==1.19.3
        Using cached numpy-1.19.3.zip (7.3 MB)
        Installing build dependencies: started
        Installing build dependencies: still running...
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting packaging
        Using cached packaging-21.3-py3-none-any.whl (40 kB)
      Collecting distro
        Using cached distro-1.7.0-py3-none-any.whl (20 kB)
      Collecting pyparsing!=3.0.5,>=2.0.2
        Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
      Building wheels for collected packages: numpy
        Building wheel for numpy (pyproject.toml): started
        Building wheel for numpy (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for numpy (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [1058 lines of output]
            Running from numpy source directory.
            numpy/random/_bounded_integers.pxd.in has not changed
            numpy/random/_philox.pyx has not changed
            numpy/random/_bounded_integers.pyx.in has not changed
            numpy/random/_sfc64.pyx has not changed
            numpy/random/_mt19937.pyx has not changed
            numpy/random/bit_generator.pyx has not changed
            Processing numpy/random/_bounded_integers.pyx
            numpy/random/mtrand.pyx has not changed
            numpy/random/_generator.pyx has not changed
            numpy/random/_pcg64.pyx has not changed
            numpy/random/_common.pyx has not changed
            Cythonizing sources
            blas_opt_info:
            blas_mkl_info:
            customize UnixCCompiler
              libraries mkl_rt not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE
      
            blis_info:
              libraries blis not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE
      
            openblas_info:
              libraries openblas not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE
      
            atlas_3_10_blas_threads_info:
            Setting PTATLAS=ATLAS
              libraries tatlas not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE
      
            atlas_3_10_blas_info:
              libraries satlas not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE
      
            atlas_blas_threads_info:
            Setting PTATLAS=ATLAS
              libraries ptf77blas,ptcblas,atlas not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE
      
            atlas_blas_info:
              libraries f77blas,cblas,atlas not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE
      
            accelerate_info:
              libraries accelerate not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
            Library accelerate was not found. Ignoring
              libraries veclib not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
            Library veclib was not found. Ignoring
              FOUND:
                extra_compile_args = ['-faltivec', '-I/System/Library/Frameworks/vecLib.framework/Headers']
                extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
                define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
      
              FOUND:
                extra_compile_args = ['-faltivec', '-I/System/Library/Frameworks/vecLib.framework/Headers']
                extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
                define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
      
            non-existing path in 'numpy/distutils': 'site.cfg'
            lapack_opt_info:
            lapack_mkl_info:
              libraries mkl_rt not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE
      
            openblas_lapack_info:
              libraries openblas not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE
      
            openblas_clapack_info:
              libraries openblas,lapack not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE
      
            flame_info:
              libraries flame not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE
      
            atlas_3_10_threads_info:
            Setting PTATLAS=ATLAS
              libraries lapack_atlas not found in /Library/Frameworks/Python.framework/Versions/3.9/lib
              libraries tatlas,tatlas not found in /Library/Frameworks/Python.framework/Versions/3.9/lib
              libraries lapack_atlas not found in /usr/local/lib
              libraries tatlas,tatlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib
              libraries tatlas,tatlas not found in /usr/lib
            <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
              NOT AVAILABLE
      
            atlas_3_10_info:
              libraries lapack_atlas not found in /Library/Frameworks/Python.framework/Versions/3.9/lib
              libraries satlas,satlas not found in /Library/Frameworks/Python.framework/Versions/3.9/lib
              libraries lapack_atlas not found in /usr/local/lib
              libraries satlas,satlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib
              libraries satlas,satlas not found in /usr/lib
            <class 'numpy.distutils.system_info.atlas_3_10_info'>
              NOT AVAILABLE
      
            atlas_threads_info:
            Setting PTATLAS=ATLAS
              libraries lapack_atlas not found in /Library/Frameworks/Python.framework/Versions/3.9/lib
              libraries ptf77blas,ptcblas,atlas not found in /Library/Frameworks/Python.framework/Versions/3.9/lib
              libraries lapack_atlas not found in /usr/local/lib
              libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib
              libraries ptf77blas,ptcblas,atlas not found in /usr/lib
            <class 'numpy.distutils.system_info.atlas_threads_info'>
              NOT AVAILABLE
      
            atlas_info:
              libraries lapack_atlas not found in /Library/Frameworks/Python.framework/Versions/3.9/lib
              libraries f77blas,cblas,atlas not found in /Library/Frameworks/Python.framework/Versions/3.9/lib
              libraries lapack_atlas not found in /usr/local/lib
              libraries f77blas,cblas,atlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib
              libraries f77blas,cblas,atlas not found in /usr/lib
            <class 'numpy.distutils.system_info.atlas_info'>
              NOT AVAILABLE
      
              FOUND:
                extra_compile_args = ['-faltivec', '-I/System/Library/Frameworks/vecLib.framework/Headers']
                extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
                define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
      
            /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
              warnings.warn(msg)
            running bdist_wheel
            running build
            running config_cc
            unifing config_cc, config, build_clib, build_ext, build commands --compiler options
            running config_fc
            unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
            running build_src
            build_src
            building py_modules sources
            building library "npymath" sources
            Could not locate executable gfortran
            Could not locate executable f95
            Could not locate executable f90
            Could not locate executable f77
            Could not locate executable xlf90
            Could not locate executable xlf
            Could not locate executable ifort
            Could not locate executable ifc
            Could not locate executable g77
            Could not locate executable g95
            Could not locate executable pgfortran
            don't know how to compile Fortran code on platform 'posix'
              adding 'build/src.macosx-10.9-universal2-3.9/numpy/core/src/npymath' to include_dirs.
            None - nothing done with h_files = ['build/src.macosx-10.9-universal2-3.9/numpy/core/src/npymath/npy_math_internal.h']
            building library "npysort" sources
              adding 'build/src.macosx-10.9-universal2-3.9/numpy/core/src/common' to include_dirs.
            None - nothing done with h_files = ['build/src.macosx-10.9-universal2-3.9/numpy/core/src/common/npy_sort.h', 'build/src.macosx-10.9-universal2-3.9/numpy/core/src/common/npy_partition.h', 'build/src.macosx-10.9-universal2-3.9/numpy/core/src/common/npy_binsearch.h']
            building library "npyrandom" sources
            building extension "numpy.core._multiarray_tests" sources
            building extension "numpy.core._multiarray_umath" sources
              adding 'build/src.macosx-10.9-universal2-3.9/numpy/core/src/umath' to include_dirs.
              adding 'build/src.macosx-10.9-universal2-3.9/numpy/core/src/npymath' to include_dirs.
              adding 'build/src.macosx-10.9-universal2-3.9/numpy/core/src/common' to include_dirs.
            numpy.core - nothing done with h_files = ['build/src.macosx-10.9-universal2-3.9/numpy/core/src/umath/funcs.inc', 'build/src.macosx-10.9-universal2-3.9/numpy/core/src/umath/simd.inc', 'build/src.macosx-10.9-universal2-3.9/numpy/core/src/umath/loops.h', 'build/src.macosx-10.9-universal2-3.9/numpy/core/src/umath/matmul.h', 'build/src.macosx-10.9-universal2-3.9/numpy/core/src/umath/clip.h', 'build/src.macosx-10.9-universal2-3.9/numpy/core/src/npymath/npy_math_internal.h', 'build/src.macosx-10.9-universal2-3.9/numpy/core/src/common/templ_common.h', 'build/src.macosx-10.9-universal2-3.9/numpy/core/include/numpy/config.h', 'build/src.macosx-10.9-universal2-3.9/numpy/core/include/numpy/_numpyconfig.h', 'build/src.macosx-10.9-universal2-3.9/numpy/core/include/numpy/__multiarray_api.h', 'build/src.macosx-10.9-universal2-3.9/numpy/core/include/numpy/__ufunc_api.h']
            building extension "numpy.core._umath_tests" sources
            building extension "numpy.core._rational_tests" sources
            building extension "numpy.core._struct_ufunc_tests" sources
            building extension "numpy.core._operand_flag_tests" sources
            building extension "numpy.fft._pocketfft_internal" sources
            building extension "numpy.linalg.lapack_lite" sources
            building extension "numpy.linalg._umath_linalg" sources
            building extension "numpy.random._mt19937" sources
            building extension "numpy.random._philox" sources
            building extension "numpy.random._pcg64" sources
            building extension "numpy.random._sfc64" sources
            building extension "numpy.random._common" sources
            building extension "numpy.random.bit_generator" sources
            building extension "numpy.random._generator" sources
            building extension "numpy.random._bounded_integers" sources
            building extension "numpy.random.mtrand" sources
            building data_files sources
            build_src: building npy-pkg config files
            running build_py
            creating build/lib.macosx-10.9-universal2-3.9
            creating build/lib.macosx-10.9-universal2-3.9/numpy
            copying numpy/conftest.py -> build/lib.macosx-10.9-universal2-3.9/numpy
            copying numpy/version.py -> build/lib.macosx-10.9-universal2-3.9/numpy
            copying numpy/_globals.py -> build/lib.macosx-10.9-universal2-3.9/numpy
            copying numpy/__init__.py -> build/lib.macosx-10.9-universal2-3.9/numpy
            copying numpy/dual.py -> build/lib.macosx-10.9-universal2-3.9/numpy
            copying numpy/_distributor_init.py -> build/lib.macosx-10.9-universal2-3.9/numpy
            copying numpy/setup.py -> build/lib.macosx-10.9-universal2-3.9/numpy
            copying numpy/ctypeslib.py -> build/lib.macosx-10.9-universal2-3.9/numpy
            copying numpy/matlib.py -> build/lib.macosx-10.9-universal2-3.9/numpy
            copying numpy/_pytesttester.py -> build/lib.macosx-10.9-universal2-3.9/numpy
            copying build/src.macosx-10.9-universal2-3.9/numpy/__config__.py -> build/lib.macosx-10.9-universal2-3.9/numpy
            creating build/lib.macosx-10.9-universal2-3.9/numpy/compat
            copying numpy/compat/py3k.py -> build/lib.macosx-10.9-universal2-3.9/numpy/compat
            copying numpy/compat/__init__.py -> build/lib.macosx-10.9-universal2-3.9/numpy/compat
            copying numpy/compat/setup.py -> build/lib.macosx-10.9-universal2-3.9/numpy/compat
            copying numpy/compat/_inspect.py -> build/lib.macosx-10.9-universal2-3.9/numpy/compat
            creating build/lib.macosx-10.9-universal2-3.9/numpy/compat/tests
            copying numpy/compat/tests/__init__.py -> build/lib.macosx-10.9-universal2-3.9/numpy/compat/tests
            copying numpy/compat/tests/test_compat.py -> build/lib.macosx-10.9-universal2-3.9/numpy/compat/tests
            creating build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/umath.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/fromnumeric.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/_dtype.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/_add_newdocs.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/_methods.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/_internal.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/_string_helpers.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/multiarray.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/_asarray.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/records.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/__init__.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/setup_common.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/memmap.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/overrides.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/getlimits.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/_dtype_ctypes.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/defchararray.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/shape_base.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/machar.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/setup.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/numeric.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/function_base.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/einsumfunc.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/umath_tests.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/_ufunc_config.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/_exceptions.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/numerictypes.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/_type_aliases.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/cversions.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/arrayprint.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            copying numpy/core/code_generators/generate_numpy_api.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core
            creating build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/test_numerictypes.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/test_scalar_methods.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/test_scalarmath.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/test_item_selection.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/test_machar.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/test_unicode.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/test_arrayprint.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/test_scalarbuffer.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/test_indexerrors.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/test_print.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/test_half.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/test_mem_overlap.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/test_shape_base.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/test_deprecations.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/__init__.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/test_errstate.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/test_records.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/test_scalarinherit.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests
            copying numpy/core/tests/test_indexing.py -> build/lib.macosx-10.9-universal2-3.9/numpy/core/tests

**Comment by clgwlg** [comment]
你好，为了更快的调查问题，请提供相关的环境信息
**环境信息**
 - Python version
 - OS
 - Flybirds version
 - 如果本地曾安装过 numpy，请提供numpy version

**Comment by shijie233** [comment]
MacBook Pro, MAC OS 12.2. Apple M1 Pro
<img width="372" alt="image" src="https://user-images.githubusercontent.com/102729268/179403650-da00f536-a014-4181-af3d-38085fa4750d.png">

**Comment by shijie233** [comment]
numpy version:
1.22.3

**Comment by clgwlg** [comment]
你遇到的这个问题很可能和 Apple M1有关，解决方案参考以下链接
https://github.com/scipy/scipy/issues/13409
