### ISSUE TITLE
建议web测试增加浏览器窗口大小控制及运行结束后是否关闭浏览器设置

### ISSUE THREAD

**Issue by Rickgao123456** [ctripcorp/flybirds#89]
建议web测试增加浏览器窗口大小控制及运行结束后是否关闭浏览器设置

**Comment by clgwlg** [comment]
支持 Browser Context 以下属性可配置：[PlayWright API ](https://playwright.dev/python/docs/emulation)
1. viewport
2. user_agent
3. locale
4. timezone
5. permissions
6. Geolocation
7. devices

**Comment by xiaoxiaocaiiao** [comment]
关闭浏览器可以用 debug来实现

**Comment by xiaoxiaocaiiao** [comment]
使用如下配置 控制浏览器：
 "emulatedDevice": null,
    "userAgent": null,
    "width": null,
    "height": null,
    "locale": null,
    "timezone": null,
    "deviceScaleFactor": null,
    "hasTouch": null,
    "geolocation": null,
    "permissions": null

**Comment by clgwlg** [comment]
v0.4.1 已支持以上Web参数
