### ISSUE TITLE
centOS执行脚本报错，提示HOOK-ERROR in before_all: AttributeError: 'PluginProxy' object has no attribute 'device_connect'

### ISSUE THREAD

**Issue by ericchen82** [ctripcorp/flybirds#9]
**问题描述 / Describe the bug**
centOS执行脚本报错，提示HOOK-ERROR in before_all: AttributeError: 'PluginProxy' object has no attribute 'device_connect'

**截图 / Screenshots**
第一个问题：
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/6082281/155289665-975cff9b-02d6-4571-b68c-dafb0eeb007d.png">
这个目录下文件存在，没有问题
<img width="961" alt="image" src="https://user-images.githubusercontent.com/6082281/155290235-243ede36-aa0f-456b-82bd-c4dad3f77277.png">

第二个问题：
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/6082281/155289960-a9407d71-96cd-4831-a9b5-f4cd893a8350.png">

**环境信息 / Environment (please complete the following information):**
 - OS: centOS7

**Comment by DHpie** [comment]
这个看起来是 查找路径时，大小写未兼容造成的。 请将 【flybirds_config.json】的 **platform** 项配置成 全小写（**android**） 后再尝试一下。 
感谢提问，我们后期会将修复代码进行上传。

**Comment by tonylin3409** [comment]
我今天也遇到了这个问题

**Comment by ericchen82** [comment]
> 看起来，这与大小写不兼容时查找路径。请将[flybirds_config.json]的**平台**项配置为全下写（**安卓**），然后再尝试。
> 感谢提问，我们上传修复代码。

配置中改成小写android，报ImportError: cannot import name '_registerMatType' from 'cv2.cv2' (/usr/local/lib/python3.8/site-packages/cv2/cv2.cpython-38-x86_64-linux-gnu.so)错误
通过安装# pip3 install opencv-python-headless==4.1.2.30临时解决

**Comment by DHpie** [comment]
> 我今天也遇到了这个问题

试试将 【flybirds_config.json】的 platform 项配置成 全小写（android）

**Comment by tonylin3409** [comment]
> 试试将 【flybirds_config.json】的 platform 项配置成 全小写（android）

修改为android后，问题已解决。
